name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training
        run: |
          python ml/train.py

      - name: Build Docker image
        run: |
          docker build -t mlops-demo .

      # Optional: push image to DockerHub
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push image
      #   run: |
      #     docker tag mlops-demo your-dockerhub-username/mlops-demo:latest
      #     docker push your-dockerhub-username/mlops-demo:latest
